### ISSUE TITLE
Cache grows too big over time

### ISSUE THREAD

**Issue by vanous** [hidroh/materialistic#929] opened 2017-07-16 12:47 UTC
I have just realized that this great HN reader is responsible for about 1GB of taken space due to catching. One idea is to show amount of taken cache in settings and include clear cache button.

Thank you

**Comment by hidroh** [comment] 2017-07-16 12:51
Hi yes we have #653 but never got around to do it yet.

**Comment by hidroh** [comment] 2017-09-02 10:53
Closing this as a duplicate of #653

**Closed by hidroh** 2017-09-02 10:53 UTC
