### ISSUE TITLE
What about proposing this amazing app to F-droid ?

### ISSUE THREAD

**Issue by ademcan** [hidroh/materialistic#23] opened 2015-06-02 09:54 UTC
Hi hidroh,

I have just installed your app and I have to say that it is amazing :)
I really like the look and it works well. I don't have the Google Play Store on my smartphone for privacy reasons, thus I mostly use apps from alternative appstores, mainly F-droid (https://f-droid.org/). I downloaded yours using the Google Play Downloader software (https://codingteam.net/project/googleplaydownloader). There are actually two apps on F-droid to read HN, but they are not as good as yours. Thus, I was wondering if you already thought about proposing Materialistic on F-droid. I think it might be a good idea.

My 2 cents...

**Comment by hidroh** [comment] 2015-06-02 10:31
Hi thanks for your support. I did take a look at f-droid before, though I'm not quite sure what would be the implications of listing my app there (e.g. deployment efforts, analytics allowed? etc). If you are familiar maybe you can give me some pointers?

**Comment by ademcan** [comment] 2015-06-02 11:27
Thank you for your quick reply.
I just had a look at the available documentation and everything in Materialistic looks OK:
https://f-droid.org/wiki/page/Inclusion_Policy
https://f-droid.org/wiki/page/Inclusion_How-To
For the submission one should create a new topic for the app in the following forum:
https://f-droid.org/forums/forum/submission-queue
Of course it is not mandatory and/or urgent, but I think that the F-droid store is missing such nice and useful applications.

**Comment by hidroh** [comment] 2015-11-09 00:54
Sorry I have decided not to publish to a 2nd store. Anyone with access to Play Store can download from there, otherwise they can build from source.

**Comment by jfreax** [comment] 2016-09-10 10:09
To be honest, it's a shame that you are not interested in F-Droid. 
F-Droid is (in my opinion) a very important and valuable project for the open source android ecosystem. Some people prefer to not use the Google Store for different reasons.

In the end, it is just a simple repository like an apt repo for Debian. You don't have to create extra builds or something like this. It really shouldn't be to much hassle to add it into the f-droid store.

If you have questions or need help, just ask. You've created a very good open source program, - let the world see it!

**Comment by hidroh** [comment] 2016-09-10 10:58
By all means I don't want Play Store to be the only place the app is available. That's why I made it available to download from Github releases as well.

Regarding F-Droid, last time I checked I need to go thru submission queue, have my app signed by F-Droid, and need to tag for it to auto recognize my update (not all my tags result in a new app version though). I also need to expose some private API keys to F-Droid build process.

All these seem to be too much a hassle for me, compared to Github releases, which though manual, it's much easier for me to just drop an APK when I have new update. The app downloaded from Github and Play Store are compatible and users can switch to either one anytime.

**Comment by igoralmeida** [comment] 2016-09-11 13:03
Some clarifications:
Submission queue: someone else can submit it for you
Tag: just respect the android versionCode, which you probably already do, and fdroid will pick it up
Private API keys: as long as core functionality is not impaired, that can be patched out pre-build (you could help clarifying the dependencies, but you don't also have to answer questions if you don't want to)

That said, if you still think you'd have too much work to do, would you be opposed to this app appearing as-is (private functionality removed, if possible) on f-droid?

Thanks

**Comment by hidroh** [comment] 2016-09-11 19:43
Thanks for clarifications. I went thru [F-Droid wiki](https://f-droid.org/wiki/page/FAQ_-_App_Developers) once more. The 2 deal breakers for me are:

- Signing key: I have to use F-Droid key, which is some thing I'm not willing to personally. I may have another app in the future that I wish to share same signing key (e.g. for shared accounts). This will not be possible with F-Droid.
- No tracking allowed: I need basic tracking from GA & Fabric to monitor app usage and crashes. Without them I won't be able to cater for users installed from F-Droid.

Of course I can make a different flavor of the app that can be distributed on F-Droid, but I can't give it the same attention for the above reason.

**Comment by igoralmeida** [comment] 2016-09-11 20:54
You don't build (and, therefore, you don't sign), f-droid does this automatically. Until [reproducible builds](https://f-droid.org/wiki/page/Deterministic,_Reproducible_Builds) are ready, that's the only way apps are available there. Hence the notice in the FAQ:
> But do note: if an app is also distributed in an APK signed by the developer, like in the Google Play Store, then the F-Droid APK will have a different signature. 

With respect to your second point, while it is possible to have the [tracking anti-feature](https://f-droid.org/wiki/page/Antifeature:Tracking) mark, i.e. your app's tracking is not disabled by default, I would recommend you not to do so. I, for one, wouldn't install it that way, and would instead try to patch it out, giving up if this breaks anything.
Gradle flavors are quite helpful and if you are willing to do the legwork (IIUC, you'd have to change some gradle files and possibly add some conditionals in the affected java files), it would be a big help since you're the most qualified person to change the codebase.

**Comment by igoralmeida** [comment] 2016-09-11 20:56
By the way, thanks for giving this a second look :)

**Comment by hidroh** [comment] 2016-09-12 15:55
Let's just keep this discussion open for now, I'll revisit soon.

**Comment by garymoon** [comment] 2016-10-22 15:50
Reading this thread it doesn't seem anyone's aware that Materialistic is already in F-Droid. It's been there since the first of Oct 2016, and is where I found it. It's an excellent app, thank you very much!

https://f-droid.org/wiki/page/io.github.hidroh.materialistic

**Comment by hidroh** [comment] 2016-10-23 01:22
Well look like someone took the liberty of porting the app to F-Droid. I have no problem with that, it's open source anyway, though some of the features may not work the same way as the one released here.

**Comment by igoralmeida** [comment] 2016-10-23 13:02
I was pleasantly surprised to find that it was available on F-Droid. Though from the metadata https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/io.github.hidroh.materialistic.txt I have no reason to believe the app has been changed in any way from upstream (this repo).

**Comment by igoralmeida** [comment] 2016-10-25 18:18
I was pleasantly surprised to find that it was available on F-Droid. Though from the metadata https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/io.github.hidroh.materialistic.txt I have no reason to believe the app has been changed in any way from upstream (this repo).

On October 22, 2016 11:22:52 PM GMT-02:00, Ha Duy Trung <notifications@github.com> wrote:
>Well look like someone took the liberty of porting the app to F-Droid.
>I have no problem with that, it's open source anyway, though some of
>the features may not work the same way as the one released here.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/hidroh/materialistic/issues/23#issuecomment-255563879

-- 
Igor Almeida (móvel)

**Comment by hidroh** [comment] 2016-11-14 00:41
Closing this since the app has already been published to F-Droid by someone.

**Closed by hidroh** 2016-11-14 00:41 UTC
