### ISSUE TITLE
Submission on Proposed FAQ on Hn materialistic 

### ISSUE THREAD

**Issue by gutzygwin** [hidroh/materialistic#1070] opened 2018-03-19 09:25 UTC
My experience after using Hn materialistic for about some weeks now was thrilling and even more than i expected. Using the application has helped me in many ways to the point it saved a neighbor's dog from severe illness, but that's a story for the latter. It came to my awereness that there wasn't a FAQ on Hn materialistic to aid users in providing them with information and awereness regarding the andriod application. The faq proposed here can be used in addition to the outstanding functions and features on hn materialistic. 

Including a FAQ on the the application will enlighten users and draw more users, encouraging them to use the application for its diverse purposes.

Here is a link to the FAQ
https://drive.google.com/file/d/1ihxb8MX8GGppsJAmMMW89pvyJapeWh9a/view?usp=drivesdk
Corrections and judgemental criticism are welcomed. 
Thank you.

**Comment by hidroh** [comment] 2019-03-24 22:22
Duplicate of #1096

**Closed by hidroh** 2019-03-24 22:22 UTC
