### ISSUE TITLE
readability mostly broken in update

### ISSUE THREAD

**Issue by kilroythe5th** [hidroh/materialistic#725] opened 2016-10-30 01:15 UTC
the readability feature pretty much doesn't work after the latest update. Before, there would occasionally be a site it couldn't parse, but now it happens on almost every site.

**Comment by hidroh** [comment] 2016-10-31 03:10
I'm unable to reproduce. Are u using version 3.1 distributed from Play Store? Version distributed via F-Droid doesn't have full Readability support.

**Comment by kilroythe5th** [comment] 2016-10-31 21:24
That's strange. Did they not like some binary blob or something?

**Comment by kilroythe5th** [comment] 2016-10-31 21:41
Looks like it's just the one from f-droid doesn't work right, so no issue anymore

**Comment by hidroh** [comment] 2016-11-01 00:24
It's because it was not ready for F-Droid but someone else published it. I don't own it. F-Droid build does not have Readability API key which I don't make public for the obvious reason.

So I'm gonna close this as non-issue.

**Closed by hidroh** 2016-11-01 00:24 UTC

**Comment by thefzsalam** [comment] 2018-04-07 15:42
Please add this in the Readme. 
I was about to open an issue.
