### ISSUE TITLE
Obtrusive Fullscreen icon when viewing text post

### ISSUE THREAD

**Issue by Sparkesix** [hidroh/materialistic#762] opened 2016-11-15 10:12 UTC
When you scroll through a text post, you actually cannot read the last words on 2-3 last lines because of the Fullscreen icon. It would be cool to at least be able to scroll the height of the button or more, depends on you. [Nexus 5X]
Thanks for looking into this. :)

**Comment by hidroh** [comment] 2016-11-16 01:08
Thanks for reporting. Are you talking about a post like Ask HN where it's just text? A screenshot would be greatly helpful.

**Comment by Sparkesix** [comment] 2016-11-16 07:58
Oh, sure :) [HERE](http://i.imgur.com/8Sqx36b.jpg)(imgur)
Thanks again for this great app :)

**Comment by hidroh** [comment] 2016-11-16 10:57
Got it

**Comment by hidroh** [comment] 2016-11-19 12:00
I'm unable to reproduce this. Is the screen that you talk about Article tab with readability text like the following?

![giphy](https://cloud.githubusercontent.com/assets/1978015/20455261/ba826764-ae92-11e6-846f-9674b6214a0e.gif)

**Comment by Sparkesix** [comment] 2016-11-19 12:11
I don't recall how exactly I achieved that, but now I tried it again and it's achievable in 2 ways:
1. Using volume buttons to scroll (probably the way it happened to me before)
2. Letting go of the screen before the button disappears, so that you get to the bottom of the text post by "inertia"

**Comment by hidroh** [comment] 2016-11-19 13:20
I see. For that case a simple scroll up and down gesture like above would hide it. It's too minor a use case for me to fix (plus fixing it would not be very straightforward).

**Comment by hidroh** [comment] 2016-11-23 14:14
Sorry I'm gonna close this for now, prioritize other issues. If have time I'll revisit this.

**Closed by hidroh** 2016-11-23 14:14 UTC
Labels: bug
