### ISSUE TITLE
Just installed update on Android, lost upvote

### ISSUE THREAD

**Issue by Dowwie** [hidroh/materialistic#723] opened 2016-10-28 19:39 UTC
I no longer have upvote functionality

**Comment by hidroh** [comment] 2016-11-01 03:43
Maybe you need to relogin again? I'm not sure if the OS update wipes away account stored on the phone?

**Comment by hidroh** [comment] 2016-11-14 00:30
Probably duplicate of #538

**Closed by hidroh** 2016-11-14 00:30 UTC
